Feature/layout
devv-up/frontend pull request #6
Opened 2020-03-12 11:34 UTC by devgaram

PR 내용
- 헤더, 푸터, 네비 레이아웃 수정
- 네비게이션에 검색 필터 레이아웃 적용
- 지역의 경우 데이터를 어떻게 보여줘야하는 지 아직 미정

2020-03-12 11:38 UTC, devgaram commented
[Jenkins]

2020-03-13 04:25 UTC, elliotyim requested changes
컴포넌트가 아직 화면에는 반영이 안된거죠? 제가 아직 익숙하지가 않다보니 화면에서는 잘 안보이네요

2020-03-13 04:25 UTC, yimsb01 commented on src/layout/components/Navigation/components/Category.vue
> +      :value="cat.id"
Nit: cat으로 줄여쓰는 것보다 category로 다 써주는게 좋지 않을까요?
정말 필요한 경우가 아니고는 줄이지 않고 다 써주는게 좋다고 개인적으로는 생각합니다.

2020-03-13 04:25 UTC, yimsb01 commented on src/layout/components/Navigation/components/Category.vue
> +    SearchModule.searchSubmit();
Nit: SearchModule.searchSubmit() 이 부분은 단순히 문서처럼 읽히는 코딩스타일을 선호하는 제 취향인걸수도 있는데
SearchModule.submit()이나 SearchModule.submitData()등으로 바꾸는게 좋지 않을까 싶습니다.
제가 다른 라이브러리 코드 까보길 좋아해서 많이 보는데 그런 느낌으로 많이 이름을 지었던것 같아요.
(아니면 그냥 영어 특유의 중복을 싫어하는 그런거 일수도..)

2020-03-13 04:29 UTC, elliotyim requested changes
리뷰를 잘못해서 두 개로 나눴네요 죄송합니다.

2020-03-13 04:29 UTC, yimsb01 commented on src/store/modules/search.ts
> +      path: "/",
제가 아직 @Action 어노테이션에 대해 잘 몰라서 그러는데,
@Action을 붙이면 async를 붙여도 await를 안에 있는 메소드에 안 붙여줘도 자동으로 모든 메소드를 동기화시켜주는건가요?

2020-03-13 04:29 UTC, yimsb01 commented on tests/unit/components/layout/header.spec.ts
> +// localVue.use(Vuex);
개인적인 의견이지만 개발 중이라고 해도 안 쓰는 코드는 주석처리가 아니라 아예 지우는게 낫다고 생각합니다.
아니면 아예 따로 temp 파일을 만들어서 보관한다던지요

2020-03-13 04:38 UTC, yimsb01 commented on src/layout/components/Navigation/components/Category.vue
> +    this.$store.commit("SET_SEARCHCATEGORYID", categoryId);
상수들은 SET_SEARCH_CATEGORY_ID로 단어 사이사이에 언더스코어를 넣어주는게 정석이라고 합니다.
참고: https://www.freecodecamp.org/news/when-to-capitalize-your-javascript-constants-4fabc0a4a4c4/

2020-03-13 04:40 UTC, yimsb01 commented on src/layout/components/Navigation/components/Category.vue
> +    this.$store.commit("SET_SEARCHCATEGORYID", categoryId);
아..근데 이 부분은 뷰에서 어떻게 쓰이는지 잘 몰라서 이게 맞다면 그대로 두셔도 상관없지만 확실히 읽기는 힘드네요.

2020-03-13 07:51 UTC, devgaram commented on src/store/modules/search.ts
> +      path: "/",
아 이부분 나중에 API 콜하는 거 추가하려고 저렇게 했었던 것 같네요. 성빈님 말씀대로 안에 await를 추가해야되는 게 맞습니다. 근데 지금 생각해보니 API 콜 위치가 여기가 맞는 지 의문이 드네요. 이 부분은 좀 더 고민하고 수정하도록 하겠습니다.  참고로 제가 알기론 @Mutation은 동기적으로 상태 데이터 수정할 때 @Action은 비동기인 작업을 수행할 때 사용하는 게 좋다고 하네요!

2020-03-13 07:57 UTC, devgaram commented on src/layout/components/Navigation/components/Category.vue
> +    this.$store.commit("SET_SEARCHCATEGORYID", categoryId);
사실 저게 @mutation 붙은 메소드 이름이라 원래는 setSearchCategoryId 이런식으로 메서드 이름을 하려고 했는 데 다른 코드 보니깐 대문자로 해놓더라구요. @Action이랑 구분 두려고 의도같은 데... 이렇게 대문자로 할거면 언더스코어를 넣어주는 게 맞겠네요.

2020-03-13 07:58 UTC, devgaram commented on src/layout/components/Navigation/components/Category.vue
> +      :value="cat.id"
엇 저도 왠만하면 그렇게 하는 데 코딩하다가 귀찮았나봅니다. 😂😂 
수정사항 반영하도록 하겠습니다.

2020-03-24 06:58 UTC, elliotyim requested changes
일단 작업이 너무 길어지면 안되니까 이거 하나만 검토가 같이 끝나시면 Approve 드리겠습니다.

2020-03-24 07:00 UTC, elliotyim requested changes
일단 작업이 너무 길어지면 안되니까 여기 몇개만 검토가 같이 끝나시면 Approve 드리겠습니다.

2020-03-24 07:00 UTC, yimsb01 commented on src/layout/components/Header/index.vue
> +}
!important를 안쓰는 방향으로 할 수 있을까요?
!important가 당장 쓸 때는 편한데 나중에 꼬이면 답없는 녀석이라서요

2020-03-24 07:06 UTC, yimsb01 commented on src/layout/components/Navigation/index.vue
> +              </p>
화면에서 봤을 때 FILTER BY CATEGORY가 아니라 FILTER BYCATEGORY로 붙어서 나옵니다.

2020-03-24 07:06 UTC, yimsb01 commented on src/layout/components/Navigation/index.vue
> +              </p>
여기도요

2020-03-24 09:44 UTC, devgaram commented on src/layout/components/Navigation/index.vue
> +              </p>
수정했습니다.

2020-03-24 09:44 UTC, devgaram commented on src/layout/components/Navigation/index.vue
> +              </p>
수정했습니다.

2020-03-24 09:48 UTC, devgaram commented on src/layout/components/Header/index.vue
> +}
다른 방법으로는 vuetify 글로벌 변수를 수정하는 방법이 있긴해요.
여기같은 경우는 style을 스코프로 사용하기도 했고 v-app-bar는 앱 내에 한 개만 존재하는 경우라서 !important로 인해 꼬일 일은 없을 것 같아요.

2020-03-24 09:49 UTC, devgaram commented on src/layout/components/Navigation/components/Category.vue
> +      :value="cat.id"
수정했습니다.

2020-03-24 09:49 UTC, devgaram commented on src/layout/components/Navigation/components/Category.vue
> +    SearchModule.searchSubmit();
submit() 으로 수정했습니다.

2020-03-24 10:56 UTC, elliotyim approved these changes
고생하셨습니다!

2020-03-24 11:25 UTC, choitaehoon1998 approved these changes
다봤는데 혼자서 프론트 작업하시는데 수고하셨습니다 !

2020-03-24 12:03 UTC, merged