[Feature/main] 메인 페이지 포스트 리스트 UI 추가
devv-up/frontend pull request #9
Opened 2020-03-23 14:54 UTC by devgaram

- 포스트 리스트 UI 추가

2020-03-23 15:00 UTC, devgaram commented
[Jenkins]

2020-04-10 06:24 UTC, hyeonjames requested changes

2020-04-10 06:24 UTC, hyeonjames commented on src/views/main/index.vue
> +      // append new posts
이부분에 왜 아무것도 안들어가나요??

2020-04-10 06:24 UTC, hyeonjames commented on src/store/modules/board.ts
> +  public posts: Post[] = [
흠, 같은 데이터로 여러개 만들어서 테스트를 하기 위함인가요?
그렇다면 이를 만들어주는 함수로 작성해서 실행 하는게 좋을 것 같네요.
너무 양이 길어지는 것 같고, 무엇보다 인자 같은 걸 넘겨서 유연하게 만들 수 있으니까요

2020-04-10 06:41 UTC, hyeonjames requested changes

2020-04-10 06:41 UTC, hyeonjames commented on src/store/models/board.d.ts
> +  export interface PostsState {
네이밍이 조금 어색하네요..
`CategoryTagState`도 네이밍이 어색한 느낌이 있어요, 무엇보다 다른 필드가 추가된다면 이름도 바꿔야 될만한 이름이라서 별로 좋은 생각이 아닌것 같네요.
posts, categories, tags 세개 다 합쳐서 BoardState로 하시는게 어떤가 싶네요.

2020-04-10 10:41 UTC, hyeonjames requested changes

2020-04-10 10:41 UTC, hyeonjames commented on src/views/main/index.vue
> +    // eslint-disable-next-line prefer-const
넣은 이유가 뭘까요?
마음대로 eslint를 끄고 키는거면, eslint의 의미가 없어요.
eslint-disable 은 진짜 필요한 경우 아니라면 추천하지 않습니다.

2020-04-18 02:37 UTC, devgaram commented on src/views/main/index.vue
> +      // append new posts
나중에 스크롤 페이징 추가하려고 만들어놨는데 이 PR에는 필요 없을 듯해서 지우고 다시 푸시했습니다.

2020-04-18 02:39 UTC, devgaram commented on src/store/modules/board.ts
> +  public posts: Post[] = [
고민하다가 아예 테스트 데이터는 JSON 파일로 빼고 나중에 API 통신할 때 사용하려고 Axios로 JSON 데이터를 불러오는 방식으로 수정했습니다.

2020-04-18 02:41 UTC, devgaram commented on src/store/models/board.d.ts
> +  export interface PostsState {
넵 CategoryTagState, PostsCategory를 합쳐서 BoardState로 만들었습니다.

2020-04-18 02:41 UTC, devgaram commented on src/views/main/index.vue
> +    // eslint-disable-next-line prefer-const
넵 삭제했습니다.

2020-04-19 11:12 UTC, dbzero4143 commented on src/components/GridList/index.vue
> +</template>
데스크탑으로 보는거랑 노트북으로 보는거랑 이미지 간격이 안맞는데 이건 미디어 쿼리 안해서 그런거죠??

2020-05-03 20:09 UTC, closed without merging